# Generated by Django 3.2.4 on 2021-06-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_marker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='description',
        ),
    ]
