# Generated by Django 3.2.4 on 2021-06-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_marker', '0002_remove_imageuploadmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('address', models.TextField()),
            ],
        ),
    ]
