# Generated by Django 3.2.4 on 2021-07-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_marker', '0004_alter_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
