# Generated by Django 3.2.4 on 2021-07-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_marker', '0005_auto_20210705_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploadmodel',
            name='document_url',
            field=models.URLField(null=True),
        ),
    ]
