# Generated by Django 3.2.4 on 2021-07-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_marker', '0006_imageuploadmodel_document_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='document_url',
        ),
    ]
